name: Combine XCFramework FX

on:
  schedule:
    - cron: '0 4 * * *' # run at 4 AM UTC
  workflow_dispatch:

jobs:
  build-openjdk-fx:
    uses: ./.github/workflows/build-openjdk-fx.yml

  build-openjdk-fx-sim:
    uses: ./.github/workflows/build-openjdk-fx-sim.yml

  build-openjdk-fx-macos:
    uses: ./.github/workflows/build-openjdk-fx-macos.yml

  combine:
    needs: [ build-openjdk-fx, build-openjdk-fx-sim, build-openjdk-fx-macos ]
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download JDK for macOS
        uses: actions/download-artifact@v4
        with:
          name: macos-jdk-fx
          path: ./macos-jdk

      - name: Download java-modules for device
        uses: actions/download-artifact@v4
        with:
          name: java-modules-device
          path: ./java-modules-fx-device

      - name: Create modules jimage for device
        run: |
          chmod +x ./macos-jdk/bin/jmod
          chmod +x ./macos-jdk/bin/jlink
          
          mkdir jmods-device
          module_names=("java.base" "java.desktop" "java.prefs" "java.xml" "java.datatransfer" "javafx.base" "javafx.graphics" "javafx.controls")
          for item in "${module_names[@]}"; do
            ./macos-jdk/bin/jmod create --class-path "./java-modules-device/$item" --target-platform ios-aarch64 "jmods-device/$item.jmod"
          done
          
          ./macos-jdk/bin/jlink --module-path ./jmods-device --add-modules javafx.controls --output java_bundle-device

      - name: Download java-modules for simulator
        uses: actions/download-artifact@v4
        with:
          name: java-modules-fx-simulator
          path: ./java-modules-simulator/java.base

      - name: Create modules jimage for simulator
        run: |
          mkdir jmods-simulator
          module_names=("java.base" "java.desktop" "java.prefs" "java.xml" "java.datatransfer" "javafx.base" "javafx.graphics" "javafx.controls")
          for item in "${module_names[@]}"; do
            ./macos-jdk/bin/jmod create --class-path "./java-modules-device/$item" --target-platform ios-aarch64 "jmods-simulator/$item.jmod"
          done
          ./macos-jdk/bin/jlink --module-path ./jmods-simulator --add-modules javafx.controls --output java_bundle-simulator

      - name: Download and unzip mobile-support
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download libffi-build -p "libffi-ios.zip" -p "libffi-ios-sim.zip"
          unzip libffi-ios.zip -d libffi-ios
          unzip libffi-ios-sim.zip -d libffi-ios-sim

      - name: Download device artifact
        uses: actions/download-artifact@v4
        with:
          name: libs-fx-device
          path: ./device

      - name: Download simulator artifact
        uses: actions/download-artifact@v4
        with:
          name: libs-fx-simulator
          path: ./simulator

      - name: Create XCFramework
        run: |
          chmod +x .github/scripts/build-xcframework-fx.sh
          .github/scripts/build-xcframework-fx.sh

      - name: Compress XCFramework and modules jimage
        run: |
          zip -r macos-jdk-fx.zip macos-jdk
          zip -r OpenJDK-FX.xcframework.zip OpenJDK-FX.xcframework
          zip -r java_bundle-fx-device.zip java_bundle-device
          zip -r java_bundle-fx-simulator.zip java_bundle-simulator

      - name: Upload XCFramework and modules jimage
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./OpenJDK-FX.xcframework
            ./java_bundle-fx-device
            ./java_bundle-fx-simulator

      - name: Create snapshot release
        uses: softprops/action-gh-release@v2
        with:
          name: "Snapshot release"
          tag_name: snapshot
          prerelease: true
          files: |
            macos-jdk-fx.zip
            OpenJDK-FX.xcframework.zip
            java_bundle-fx-device.zip
            java_bundle-fx-simulator.zip
